### ISSUE TITLE
bug: "--version" flag cannot be used

### ISSUE THREAD

**Issue by dqhl76** [tensorchord/envd-docs#177]
When I followed the development guide [development.md](https://github.com/tensorchord/envd-docs/blob/main/docs/community/development.md) Line58 `./bin/envd --version`.
It gives a problem that
`Incorrect Usage: flag provided but not defined: -version`
I think it may be a typo. If this means a `version` flag, then it shoule be `./bin/envd version`

**Comment by aseaday** [comment]
I think there is an error in our doc. You should use `envd version`

**Comment by dqhl76** [comment]
I can provide a pr to fix it. 
/assign @dqhl76

**Comment by aseaday** [comment]
> I can provide a pr to fix it. /assign @dqhl76

That would be very nice of you! Thx!
