### ISSUE TITLE
feat: add open graph protocol metadata

### ISSUE THREAD

**Issue by kemingy** [tensorchord/envd-docs#183]
This can enable the social media preview card.

Ref:

* https://ogp.me/
* https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started#opengraph

**Comment by shaonianche** [comment]
The preview card already exists, but it only works on the primary domain。[Here](https://github.com/vuejs/vitepress/issues/975) are some ways to configure other pages, it doesn't look elegant
https://github.com/tensorchord/envd-docs/blob/76637bd6b47c33e3121750a38b81ef0034ac4b25/docs/.vitepress/config.ts#L37-L45
