### ISSUE TITLE
bug: link to train.ipynb leads to 404

### ISSUE THREAD

**Issue by AlexXi19** [tensorchord/envd-docs#184]
The link to `train.ipynb` in https://envd.tensorchord.ai/envs/multitarget.html leads to a 404. Should consider linking it to the GitHub file?

**Comment by gaocegege** [comment]
Did not find `train.ipynb` on the doc page, could you please show the 404 links?

**Comment by AlexXi19** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/68758451/201035506-930c01c8-d608-4778-bd2c-74584968f303.png">

It's gone from the link I provided 🤔, but it shows in the markdown files in the GitHub repo [here](https://github.com/tensorchord/envd-docs/blob/main/docs/envs/multitarget.md) and also locally

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/68758451/201035866-b5c580f2-9766-490a-92e1-c8f9ff6f707b.png">

**Comment by gaocegege** [comment]
Weird. It should be a bug in our doc.

**Comment by gaocegege** [comment]
Could you please help fix it? The correct link should be https://github.com/tensorchord/envd/blob/main/examples/streamlit-mnist/train.ipynb

**Comment by AlexXi19** [comment]
Got it I will fix the link in the markdown but my only question is I'm not familiar with the deployment so not sure if there are any caching/CDN issues that's causing this.
