### ISSUE TITLE
feat(docs): Add more details about the installation

### ISSUE THREAD

**Issue by gaocegege** [tensorchord/envd-docs#204]
> @kemingy Yeah, we can add an installation section to [Building Your First Environment page](https://envd.tensorchord.ai/guide/build-envd.html)(P.S. the page title is different from sidebar entry :P), or in its own page. We can then make it more verbose and clear there, and leave a link referring to the docs in README. What's more, we can make a more beautiful UI for it, such as a tab component to switch different installation methods.

_Originally posted by @frostming in https://github.com/tensorchord/envd/issues/1300#issuecomment-1348192479_

**Comment by frostming** [comment]
Plan to start working on this after homebrew is ready. request to assign to me.

**Comment by kemingy** [comment]
> Plan to start working on this after homebrew is ready. request to assign to me.

Thanks for your help!
