### ISSUE TITLE
`envd` graphic in dark mode 

### ISSUE THREAD

**Issue by AlexXi19** [tensorchord/envd-docs#220]
The text is hard to read in dark mode. 

https://envd.tensorchord.ai/developers/development.html

![image](https://user-images.githubusercontent.com/68758451/208580807-c23c5d40-7703-45b4-a3be-986a66cf9f9f.png)

**Comment by gaocegege** [comment]
Thanks, it is a bug.

**Comment by VoVAllen** [comment]
fixed in #227
