### ISSUE TITLE
typo(doc):Link pointing is not working

### ISSUE THREAD

**Issue by shaonianche** [tensorchord/envd-docs#53]
Hi，The page with the link to the `guides` does not exist, in the `Community` location of the [get-started](https://github.com/tensorchord/envd-docs/blob/1cace6e7aefc9e1d0e9707508c6c0a73b26ff8ca/docs/get-started.md) page.

**Comment by gaocegege** [comment]
Thanks for the issue! I think the correct link should be https://envd.tensorchord.ai/docs/community/contributing

**Comment by gaocegege** [comment]
Are you interested in helping us fix the issue?

**Comment by shaonianche** [comment]
sure.
